// <auto-generated />
namespace BDD.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class heritageAdmin : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(heritageAdmin));
        
        string IMigrationMetadata.Id
        {
            get { return "202010301708513_heritageAdmin"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
