// <auto-generated />
namespace GestionFormation.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ajoutAdminmotdepasse : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ajoutAdminmotdepasse));
        
        string IMigrationMetadata.Id
        {
            get { return "202010312131337_ajout Admin, mot de passe"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
